# Generated by Django 3.1.5 on 2021-02-03 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
