# Generated by Django 3.1.5 on 2021-02-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210205_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 21, 56, 36, 512267)),
        ),
    ]
